### ISSUE TITLE
cannot install projects on Windows 2012 R2

### ISSUE THREAD

**Issue by joelwilson** [chocolatey/chocolatey-cookbook#36] opened 2015-04-08 00:24 UTC
I am running into an issue where the cookbook will not install any packages. This is only happening on Windows2012 R2 I get the following output:

```
==> default: [2015-04-07T16:52:17-07:00] INFO: Processing chocolatey[vs2013agents] action install (build_server::windows line 16)
==> default: [2015-04-07T16:52:18-07:00] DEBUG: Checking to see if this chocolatey package is installed/upgradable: 'vs2013agents'
==> default: [2015-04-07T16:52:22-07:00] INFO: vs2013agents already installed - nothing to do.
==> default:
==> default: [2015-04-07T16:52:22-07:00] INFO: Processing chocolatey[microsoft-build-tools] action install (build_server::windows line 16)
==> default: [2015-04-07T16:52:23-07:00] DEBUG: Checking to see if this chocolatey package is installed/upgradable: 'microsoft-build-tools'
==> default: [2015-04-07T16:52:26-07:00] INFO: microsoft-build-tools already installed - nothing to do.
```

The problem seems to stem from the fact that on Windows 7, `choco version` errors if it can't find the project, resulting in error code 1, but on Windows 2012, the command does not fail (returns code 0):

```powershell
# Win 7 (Chocolatey v0.9.8.28 and v0.9.9.4)
PS C:\Windows\system32> choco version vs2013agents -localonly
No package found
No package found
Command 'version' failed (sometimes this indicates a partial failure). Additional info/packages: vs2013agents, -localonly

Disable this message by changing ksMessage to false in chocolatey.config.
PS C:\Windows\system32> $LastExitCode
1


# Win 2012 R2
PS C:\Users\vagrant> choco version vs2013agents -localonly
Chocolatey v0.9.9.4

DEPRECATION NOTICE - `choco version -lo` is deprecated. version command
 will be removed in version 1.0.0. Please use `choco list -lo` instead.
0 packages installed.
PS C:\Users\vagrant> $LastExitCode
0
```

With this behavior, the [package_installed? method](https://github.com/chocolatey/chocolatey-cookbook/blob/master/providers/default.rb#L80-L85) will return true whether or not the package is already installed.

**Comment by ferventcoder** [comment] 2015-04-08 00:35
See #35

**Comment by ferventcoder** [comment] 2015-04-08 00:36
Duplicate of #34

**Closed by ferventcoder** 2015-04-08 00:36 UTC
Labels: duplicate

**Comment by joelwilson** [comment] 2015-04-08 15:33
Can I specify a pre-0.9.9.x version of chocolaty to install with the cookbook?

**Comment by ferventcoder** [comment] 2015-04-08 19:24
You can - https://chocolatey.org/install-lastposhclient.ps1

**Comment by joelwilson** [comment] 2015-04-08 20:21
Even better - Thanks!
