### ISSUE TITLE
Error installing chocolatey using TestKitchen / with ec2 provisioner

### ISSUE THREAD

**Issue by jedugas** [chocolatey/chocolatey-cookbook#54] opened 2015-10-08 22:53 UTC
Getting an error when installing chocolatey to a test server using testkitchen - see console dump below. Shaved the .kitchen.yml run list to just the chocolatey install for demonstration, i.e.

      run_list:
        - recipe[chocolatey::default]

The testkitchen server is a 64bit Windows 2012R2 AWS instance. Looks like it's trying to execute a bad command ("C:\Windows\system32\C:\windows\sysnative\cmd.exe" /c ...). hate to submit the issue but I can't seem to find a workaround.

thx     -/- jeff

================================================================================
Error executing action `run` on resource 'batch[install chocolatey]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of "C:\Windows\system32\C:\windows\sysnative\cmd.exe" /c "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20151008-5236-tkbbs4.bat" ----
STDOUT:
STDERR: The filename, directory name, or volume label syntax is incorrect.
---- End output of "C:\Windows\system32\C:\windows\sysnative\cmd.exe" /c "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20151008-5236-tkbbs4.bat" ----
Ran "C:\Windows\system32\C:\windows\sysnative\cmd.exe" /c "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20151008-5236-tkbbs4.bat" returned 1

Resource Declaration:
---------------------
# In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/recipes/default.rb

 48: batch 'install chocolatey' do
 49:   architecture arch
 50:   interpreter cmd
 51:   code <<-EOH
 52:     powershell -noprofile -inputformat none -noninteractive -executionpolicy bypass -EncodedCommand #{chocolatey_install_script}
 53:   EOH
 54:   not_if { ChocolateyHelpers.chocolatey_installed? }
 55: end
 56:

**Comment by jedugas** [comment] 2015-10-09 21:53
Issue exists with chef-supermarket v 0.4.0 (https://supermarket.chef.io/cookbooks/chocolatey/versions/0.0.4); reverting to chef-supermarket v 0.3.0 fixed my issue.

**Comment by ferventcoder** [comment] 2015-10-10 19:13
If the issue is still valid in the latest version (0.4.0), why did you close it?

**Comment by ferventcoder** [comment] 2015-10-13 15:08
@mwrock noticed you are not watching this repo.

**Comment by mwrock** [comment] 2015-10-13 15:56
Oh will look. I turned everything off a few weeks ago  when i got subscribed to 200 repos at once and neglected to turn this one back on.

**Comment by ferventcoder** [comment] 2015-10-13 15:58
@mwrock I know how that is. The number was a little bit higher. I basically turned off auto watch, so I have to remember to subscribe to new repos.

**Comment by wstaples** [comment] 2015-10-13 20:39
The duplication of directories on this line does not seem correct:
Ran "**C:\Windows\system32\**C:\windows\sysnative\cmd.exe"

Also this seems to work if you use chef-client 11.10 with the 0.4.0 cookbook.

**Comment by mwrock** [comment] 2015-10-13 20:43
I'm not having luck reproducing this. I'm simply running test-kitchen and converging a fresh 2012R2 box with chocolotey-cookbook::default. I'm going to continue trying to repro. You are absolutely correct that the concatenated oath is not correct. I'm hypothesizing that this is not the fault of this cookbook but perhaps a bug introduced in a new version of chef or the mixlib-shellout gem.

While I'm trying to get a repro, it would be super cool if someone could send a gist of a debug level log running into this.

**Comment by wstaples** [comment] 2015-10-13 20:56
Here is a gist containing the error:
https://gist.github.com/wstaples/97316e2643e555112c91

**Comment by mwrock** [comment] 2015-10-13 21:07
thanks @wstaples I have a solid repro now.

**Comment by wstaples** [comment] 2015-10-13 21:37
In the default recipe there is this if statement (line 27): 
```ruby
if File.exist?('C:\windows\sysnative\cmd.exe')
  arch = :x86_64
  cmd = 'C:\windows\sysnative\cmd.exe'
else
  arch = nil
  cmd = 'cmd.exe'
end
```
However it looks like the batch resource is already adding a base path. File `lib\chef\provider\batch.rb` line 32
```ruby
def command
  basepath = is_forced_32bit ? wow64_directory : run_context.node.kernel.os_info.system_directory

  interpreter_path = Chef::Util::PathHelper.join(basepath, interpreter)

   "\"#{interpreter_path}\" #{flags} \"#{script_file.path}\""
end
```
Would the easiest solution be to change the cmd variable to `cmd.exe` just like it is in the else section?

**Comment by mwrock** [comment] 2015-10-13 22:42
This is a bug in the `batch` resource introduced in chef 12.5. I'll file an issue to be fixed on that side. Simply moving to `cmd.exe` works for chef v12.5+ but for the many users on previous versions this can cause issues as was seen in #38. I'm going to look at a way to refactor this that will be both forward and backward compatible.

Going to try to have this done today but know that v12.4.3 and prior works against this cookbook version.

**Comment by erick-thompson** [comment] 2015-10-14 18:51
We are using the managed Chef server, so we can't roll back to prior versions of Chef. Any idea on timeframe? Can I assist in any way?

**Closed** 2015-10-15 14:58 UTC

**Comment by mwrock** [comment] 2015-10-15 15:08
New release 0.4.1 which fixes this has been pushed to the supermarket!

**Comment by jedugas** [comment] 2015-10-20 03:40
My bad for closing the issue prematurely - I was (unwisely) dealing with multiple changes at once so thought I might have jumped the gun by reporting it to begin with.

Thanks to Matt for providing a fix. :)

**Comment by mwrock** [comment] 2015-10-20 03:45
No worries @jedugas. Been there done that :) Report back if things don't work as expected.
